### PR TITLE
Modernize pyjq build process, achieving Python 3.12 compatibility.

### LINKED ISSUE #84: PyJQ Does Not Build in Python 3.12
I recently tried to install pyjq in a Python 3.12 environment, and encountered the following error (along with a slew of deprecation warnings, omitted): 

```text
      _pyjq.c:6953:55: error: no member named 'ob_digit' in 'struct _longobject'
                  const digit* digits = ((PyLongObject*)x)->ob_digit;
                                        ~~~~~~~~~~~~~~~~~~  ^
      _pyjq.c:7008:55: error: no member named 'ob_digit' in 'struct _longobject'
                  const digit* digits = ((PyLongObject*)x)->ob_digit;
                                        ~~~~~~~~~~~~~~~~~~  ^
      _pyjq.c:7187:55: error: no member named 'ob_digit' in 'struct _longobject'
                  const digit* digits = ((PyLongObject*)x)->ob_digit;
                                        ~~~~~~~~~~~~~~~~~~  ^
      _pyjq.c:7242:55: error: no member named 'ob_digit' in 'struct _longobject'
                  const digit* digits = ((PyLongObject*)x)->ob_digit;
                                        ~~~~~~~~~~~~~~~~~~  ^
      _pyjq.c:7693:47: error: no member named 'ob_digit' in 'struct _longobject'
          const digit* digits = ((PyLongObject*)b)->ob_digit;
```

Based on the discussion [here](https://github.com/cython/cython/issues/5238) I believe references to `ob_digit` should be changed to `->long_value->ob_digit`; I am unsure whether if there other breaking issues in 3.12.

### PR DESCRIPTION
**Pull request by choralbari**
* Remove .c file, allowing it to be generated from .pyx.
* Remove use of included library tarballs, listings as deps instead.

Fixes #84

### CODE REVIEW

**Comment by pedro-r-marques** [comment]
ref #84
